skip-check: 
  - CKV_AWS_158  # CloudWatch Log Group KMS encryption
  - CKV_AWS_338  # CloudWatch log retention 1 year
  - CKV_AWS_136  # ECR KMS encryption
  - CKV_TF_1     # Terraform module commit hash
  - CKV_AWS_24   # Security group SSH from 0.0.0.0/0
  - CKV_AWS_23   # Security group descriptions
  - CKV_AWS_382  # Security group egress
  - CKV_AWS_88   # EC2 public IP
  - CKV_AWS_79   # EC2 IMDSv1
  - CKV_AWS_135  # EC2 EBS optimized
  - CKV_AWS_126  # EC2 detailed monitoring
  - CKV_AWS_55   # S3 ignore public ACLs
  - CKV_AWS_53   # S3 block public ACLs
  - CKV_AWS_56   # S3 restrict public buckets
  - CKV_AWS_54   # S3 block public policy
  - CKV_AWS_145  # S3 KMS encryption
  - CKV_AWS_18   # S3 access logging
  - CKV2_AWS_62  # S3 event notifications
  - CKV2_AWS_6   # S3 public access block
  - CKV2_AWS_61  # S3 lifecycle configuration
  - CKV_AWS_144  # S3 cross-region replication
